# Generated by Django 5.0.1 on 2024-02-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
