# Generated by Django 5.0.1 on 2024-02-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_doctor_user_alter_userdata_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="is_blocked",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
