# Generated by Django 5.0.1 on 2024-02-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_userdata_email_alter_userdata_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
