# Generated by Django 5.0.1 on 2024-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_userdata_first_name_alter_userdata_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
    ]
